### ISSUE TITLE
Dragging outside picker should select color closest to cursor, not just between cursor and center

### ISSUE THREAD

**Issue by roryokane** [husl-colors/husl-site#12]
Say you go to [the picker](http://www.husl-colors.org/) and enter the color `#ffff00`. Then you drag the mouse onto the tip of the triangle at the bottom of the picker, and move it to the right a little bit, so it is outside of the colored polygon. You will get this:

![current color selected between cursor and center](https://cloud.githubusercontent.com/assets/79168/9508550/61dc99ee-4c24-11e5-8d12-7382154ebb0d.png)

The selected color is something like `#fffb9d`. It is the color closest to the cursor on an imaginary line from the cursor to the center of the picker.

However, it would be more intuitive if the absolute closest color to the cursor (`#ffff00` in this case) were selected instead:

![desired color selected closest to cursor](https://cloud.githubusercontent.com/assets/79168/9508552/685016ac-4c24-11e5-96c9-cc207c586b67.png)

This would also make selection less jittery when the user wants to select a color close to that sharp point but not on it. Right now, that is much harder than it feels like it should be.

The current behavior is implemented [in the function `adjustPosition` in `main.coffee`](https://github.com/husl-colors/husl-site/blob/9c5632d7b4952fdf12aafdde493268eedf0ad67d/src/main.coffee#L487-L497). It should be changed to find the closest point to the cursor that is within the displayed polygon. There is probably some standard algorithm for that, but I don’t know what it is right now. “Closest” is measured by Euclidean distance, and the polygon is defined by the allowed H and S values at that L value.

**Comment by boronine** [comment]
Thanks for the detailed description. This would make the widget feel much nicer. I'm leaving this open in case anyone gets the inspiration to find an algorithms for this.

**Comment by boronine** [comment]
Fixed!
