### ISSUE TITLE
Upside-down gamut

### ISSUE THREAD

**Issue by boronine** [husl-colors/husl-site#13]
Report: https://github.com/husl-colors/husl/issues/20

**Comment by roryokane** [comment]
> I just Google image-d for "CIE LUV" and now I see that it is indeed upside-down.

A convenient link to that image search: [“CIE LUV”](https://www.google.com/search?q=CIE+LUV&tbm=isch).

## Summary of the problem

In CIELUV’s [(<i>u′</i>, <i>v′</i>) chromaticity diagram](https://commons.wikimedia.org/wiki/File:CIE_1976_UCS.png), when you start at the right and rotate counterclockwise, you reach the primary colors in the order red, green, blue:

![CIE 1976 UCS](https://cloud.githubusercontent.com/assets/79168/10712959/50d71dfe-7a78-11e5-8d33-0c15355d64ee.png)

But on [the current interactive color picker](http://www.husl-colors.org/), the order is red, blue, green. The image has roughly been flipped vertically:

![current HUSL site’s color diagram](https://cloud.githubusercontent.com/assets/79168/10712966/94c8d250-7a78-11e5-8160-45819b371001.png)

**Comment by boronine** [comment]
Finally fixed :)
